// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN20XqxnnYgF55R4ohMFTTypYK0xfRlZM',
    appId: '1:549474370704:web:a79258cc53e1d3d9ee4415',
    messagingSenderId: '549474370704',
    projectId: 'kyat-keeper',
    authDomain: 'kyat-keeper.firebaseapp.com',
    storageBucket: 'kyat-keeper.appspot.com',
    measurementId: 'G-66QT9DPFKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUNnWVAtCVVsWBwqpmg6EuBfRoeX3QrNQ',
    appId: '1:549474370704:android:d16b0921f99459a9ee4415',
    messagingSenderId: '549474370704',
    projectId: 'kyat-keeper',
    storageBucket: 'kyat-keeper.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkHcidGnwLDMLUB8BjgbNNLv6rtYrQBrQ',
    appId: '1:549474370704:ios:48f20848ae141745ee4415',
    messagingSenderId: '549474370704',
    projectId: 'kyat-keeper',
    storageBucket: 'kyat-keeper.appspot.com',
    iosClientId: '549474370704-3lvgcfc7ou7o9cpde8p4lfbda91jnbhg.apps.googleusercontent.com',
    iosBundleId: 'com.waiyanminkhant.xybertracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkHcidGnwLDMLUB8BjgbNNLv6rtYrQBrQ',
    appId: '1:549474370704:ios:c4fdee71a2a07b20ee4415',
    messagingSenderId: '549474370704',
    projectId: 'kyat-keeper',
    storageBucket: 'kyat-keeper.appspot.com',
    iosClientId: '549474370704-69mnu7h0t9o3t26mh3ejak2mitfn31ov.apps.googleusercontent.com',
    iosBundleId: 'com.waiyanminkhant.xybertracker.RunnerTests',
  );
}
